import sys,os

gslpath = os.environ['CORAL_GSLPATH']
x11path = os.environ['CORAL_X11PATH']
coralhome = os.environ['CORAL_HOME']
ccflags = os.environ['CORAL_CCFLAGS']
msuhydrohome = os.environ['MSUHYDRO_HOME']
h5home = os.environ['CORAL_HDF5_HOME']

os.system('scons -C '+coralhome)

b3denv = Environment( \
  CPPPATH = ['#include','#src/b3d','#src/analyze',coralhome+'include', gslpath+'include', h5home+'include'],\
	LIBPATH = ['#lib', coralhome+'lib', gslpath+'lib', h5home+'lib'],\
	LIBS = ['coralutils','gsl','gslcblas', 'b3d', 'hdf5_cpp', 'hdf5_hl_cpp', 'hdf5', 'hdf5_hl', 'sz', 'z'],\
	CCFLAGS = ccflags, \
	LDFLAGS = '',\
	#ENV = \{'PATH':os.environ['PATH']\}\
)

SConscript('src/b3d/SConscript', exports='b3denv', build_dir='#build/b3d', duplicate=0)
SConscript('src/analyze/SConscript', exports='b3denv', build_dir='#build/analyze', duplicate=0)
