import sys,os

if os.environ.has_key("CORAL_GSLPATH"):gslpath = os.environ['CORAL_GSLPATH']
else:                                  gslpath = "/sw/"
if os.environ.has_key("CORAL_X11PATH"):x11path = os.environ['CORAL_X11PATH']
else:                                  x11path = "/sw/"
if os.environ.has_key("CORAL_HOME"): coralhome = os.environ['CORAL_HOME']
else:                                coralhome = os.getcwd()
if os.environ.has_key("CORAL_CCFLAGS"):ccflags = os.environ['CORAL_CCFLAGS']
else:                                  ccflags = ""
#ccflags += " -Df2cFortran -ansi"

opts = Variables()
opts.Add( BoolVariable( 'debug',    'Set to true to build for debugging', 0 ) )
opts.Add( BoolVariable( 'X11',      'Build libraries dependent on X11', 1 ) )
opts.Add( BoolVariable( 'tests',    'Build regression tests', 0 ) )


# --------------- Default Build Environment ---------------
coralenv = Environment( \
options = opts,\
    CPPPATH = [ '#include', '#src', gslpath+'include' ],\
    LIBPATH = [ '#lib', gslpath+'lib' ],\
    LIBS    = [ 'gsl', 'gslcblas' ],\
    CCFLAGS = ccflags, \
    LDFLAGS = '',\
    #ENV = \{'PATH':os.environ['PATH']\}\
)

if coralenv['debug']: coralenv['CCFLAGS'] += " -Wall -g -DTNT_BOUNDS_CHECK"

SConscript('src/coralutils/SConscript', exports='coralenv', variant_dir='#build/coralutils', duplicate=0)
SConscript('src/coral/SConscript', exports='coralenv', variant_dir='#build/coral', duplicate=0)

if coralenv['X11']: 
    coralenv[ 'CPPPATH' ] += [ x11path+'include' ]
    coralenv[ 'LIBPATH' ] += [ x11path+'lib' ]
    coralenv[ 'LIBS' ]    += [ 'X11']  # for some reason, adding to this list on MacOSX messes up CheckLib calls later

    # --------------- Build XGraph ---------------
    SConscript('src/xgraph/SConscript', exports='coralenv', variant_dir='#build/xgraph', duplicate=0)

Help(opts.GenerateHelpText(coralenv))

conf = Configure(coralenv)
#for lib in coralenv['LIBS']:
#    if not conf.CheckLib(lib):
#        print 'Did not find '+lib+' in '+str(coralenv['LIBPATH'])+', exiting!'
#        #Exit(1)
#        coralenv = conf.Finish()

# --------------- Build CorAL & Friends ---------------
SConscript('src/coralutils/SConscript', exports='coralenv', variant_dir='#build/coralutils', duplicate=0)
SConscript('src/coral/SConscript', exports='coralenv', variant_dir='#build/coral', duplicate=0)
SConscript('src/xgraph/SConscript', exports='coralenv', variant_dir='#build/xgraph', duplicate=0)

# --------------- Build regression tests ---------------
#if coralenv['tests']: 
#    SConscript( 'codetests/SConscript', exports = 'coralenv', variant_dir = '#build/tests', duplicate = 0 )

