function [ OUT ] = comment2struct( comment )
%comment2struct this takes a comment in text or latex form generated by
%struct2comment.m and converts it back into a matlab structure.
%   comment2struct this takes a comment in text or latex form generated by
%struct2comment.m and converts it back into a matlab structure. Note that
%the original structure will be the only field of OUT. For example, a
%variable FOOBAR converted to text will be translated back into the field
%OUT.FOOBAR. Only the text version of translating and re-importing works at
%the moment, but latex support is planned.
%
%The main mechanism of recreating a complex structure array is using the
%setfield functionality, specifically its ability to set fields multiple
%levels deep if the field's "path" is defined in a cell array and
%enumerated in the function call. For example, if we wanted
%CONFIG.OPTIONS.MCMC.MaxT = 2000, we could create a cell array fieldpath =
%{OPTIONS MCMC MaxT} and call CONFIG = setfield(CONFIG, fieldpath{:}, 2000)

OUT = struct();

%break the comment up into individual lines
comment = textscan(comment, '%s','delimiter','\n');
comment = comment{1}.';

start=1;
while start <= size(comment,2)
    displaystring = textscan(comment{start},'%s');
    displaystring = displaystring{1}.';
    
    if(strcmp(displaystring{1},'#DISPTYPE') == 1 || strcmp(displaystring{1},'\#DISPTYPE') == 1)
        break;
    else
        start = start+1;
        if(start>size(comment,2))
            error('Comment is formatted incorrectly; the #DISPTYPE flag must appear at the front of a line.');
        end
    end
end

%extract display type and re-import accordingly
displaytype = displaystring{3};

switch displaytype
    case 'text' 
        %the current tier of the structure
        currentcategory = [];
        %A cell array of higher tiers
        parents = [];

        for i = (start+1):size(comment,2)
            %Break each line up into individual words and parse seperately
            words = textscan(comment{i}, '%s');
            words = words{1}.';
            switch words{1}
                case '#VARIABLE'
                    parents = words(2);
                case '#CATEGORY'
                    currentcategory = words(2);
                    parents = (words(4:end));
                case '#TYPE'
                    %set the fields. See above for details.
                    switch words{2}
                        case 'logical'
                            fieldpath = [parents, currentcategory, words(3)];
                            
                            if(size(words,2) > 4)
                                if(strcmp(words{5}, 'true'))
                                    OUT = setfield(OUT, fieldpath{:}, true);
                                elseif(strcmp(words{5}, 'false'))
                                    OUT = setfield(OUT, fieldpath{:}, false);
                                end
                            else %empty field in the original structure
                                OUT = setfield(OUT,fieldpath{:},'');
                            end
                       case 'char'
                            fieldpath = [parents, currentcategory, words(3)];

                            if(size(words,2) > 4)
                                OUT = setfield(OUT, fieldpath{:}, words{5:end}); %doing {5:end} covers char arrays
                            else
                                OUT = setfield(OUT, fieldpath{:}, '');
                            end

                        case 'double'
                            fieldpath = [parents, currentcategory, words(3)];

                            if(size(words, 2) > 4)
                                OUT = setfield(OUT, fieldpath{:}, str2double(words(5:end))');
                            else
                                OUT = setfield(OUT, fieldpath{:}, '');
                            end

                        case 'cell'
                            fieldpath = [parents, currentcategory, words(4)];
                            switch words{3}
                                case 'double'
                                    %Convert cell array of strings to array
                                    %of doubles, and array of doubles back
                                    %to cell array
                                    tempcellarray = num2cell(str2double(words(6:end)));
                                case 'char'
                                    tempcellarray = words(6:end);
                                case 'empty'
                                    tempcellarray = {};
                                otherwise
                                    error(['Unknown cell array type ' words{2}]);
                            end
                            OUT = setfield(OUT, fieldpath{:}, tempcellarray');
                        otherwise
                            error(['Unknown data type ' words{2}]);
                    end
                case '#END' %Go up a tier in structure
                    if(~isempty(parents))
                        currentcategory = parents(end);
                        parents = parents(1:end-1);
                    end
                otherwise
                    error(['Unknown tag ' words{1}]);
            end
        end
    case 'latex'
        currentcategory = [];
        parents = [];
        
        for i = (start+1):size(comment,2)
            %Break each line up into individual words and parse seperately
            words = textscan(comment{i}, '%s');
            words = words{1}.';
            switch words{1}
                case '\item'
                    switch words{2}
                        case '\#CATEGORY'
                            words(3) = strrep(words(3), '\_', '_');
                            currentcategory = words(3);
                            parents = (words(5:end));
                        case '\#TYPE'
                            %set the fields. See above for details.
                            switch words{3}
                                case 'logical'
                                    field = strrep(words{4}, '\_','_');
                                    fieldpath = [parents, currentcategory, {field}];
                                    if(size(words,2) > 5)
                                        if(strcmp(words{6}, 'true'))
                                            OUT = setfield(OUT, fieldpath{:}, true);
                                        elseif(strcmp(words{6}, 'false'))
                                            OUT = setfield(OUT, fieldpath{:}, false);
                                        end
                                    else %empty field in the original structure
                                        OUT = setfield(OUT,fieldpath{:},'');
                                    end
                               case 'char'
                                    field = strrep(words{4}, '\_','_');
                                    fieldpath = [parents, currentcategory, field];

                                    if(size(words,2) > 5)
                                        for j = 6:size(words,2)
                                            words{j} = strrep(words{j}, '\_', '_');
                                        end
                                        OUT = setfield(OUT, fieldpath{:}, words{6:end}); %doing {5:end} covers char arrays
                                    else
                                        OUT = setfield(OUT, fieldpath{:}, '');
                                    end

                                case 'double'
                                    field = strrep(words{4}, '\_','_');
                                    fieldpath = [parents, currentcategory, field];

                                    if(size(words, 2) > 5)
                                        OUT = setfield(OUT, fieldpath{:}, str2double(words(6:end))');
                                    else
                                        OUT = setfield(OUT, fieldpath{:}, '');
                                    end

                                case 'cell'
                                    field = strrep(words{5}, '\_','_');
                                    fieldpath = [parents, currentcategory, field];
                                    
                                    switch words{4}
                                        case 'double'
                                            %Convert cell array of strings to array
                                            %of doubles, and array of doubles back
                                            %to cell array
                                            tempcellarray = num2cell(str2double(words(7:end)));
                                        case 'char'
                                            for j = 7:size(words,2)
                                                words{j} = strrep(words{j}, '\_', '_');
                                            end
                                            tempcellarray = words(7:end);                           
                                        otherwise
                                            error(['Unknown cell array type ' words{4}]);
                                    end
                                    OUT = setfield(OUT, fieldpath{:}, tempcellarray);
                                otherwise
                                    error(['Unknown data type ' words{3}]);
                            end
                            
                        otherwise
                            error(['Unknown tag ' words{2}]);
                    end
                case {'\begin{itemize}', '\end{document}'}
                case '\end{itemize}'
                    if(~isempty(parents))
                        currentcategory = parents(end);
                        parents = parents(1:end-1);
                    end
                case '\#VARIABLE'
                    parents = words{2};
                otherwise
                    error(['Unknown tag ' words{1}]);
            end
        end
    otherwise
        error(['Unknown display type ' displaytype]);
end


