import sys,os
Import('coralenv')

inclist = Split(' \
Arrays/arrays.h \
GSLMatrix/gslmatrix.h \
Misc/misc.h \
NumMath/constants.h \
NumMath/random.h \
ParameterMap/parametermap.h \
SpecialFunctions/Chebyshev/chebyshev.h \
SpecialFunctions/Chebyshev/chebyshev_fit.h \
SpecialFunctions/sf.h \
utilities.h \
')

coralenv.Install('#include', [inclist])

srclist = Split(' \
Arrays/arraycalc.cc \
Arrays/charray.cc \
Arrays/mclist.cc \
Arrays/threed.cc \
Arrays/ylmarray.cc \
GSLMatrix/gslmatrix.cc \
Misc/misc.cc \
NumMath/random.cc \
ParameterMap/parametermap.cc \
SpecialFunctions/Bessel/bess.cc \
SpecialFunctions/CartesianHarmonics/chcalc.cc \
SpecialFunctions/CoulWave/coulwave.cc \
SpecialFunctions/Ylm/ylm.cc \
')

utilities_lib = coralenv.Library('coralutils', source = [srclist])
coralenv.Install('#lib',utilities_lib)
